server:
  port: 9000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tours_secure_vue_jwt
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
jwt:
  secret: ServletservicforservletdispatcherServletincontextwithpathuyhjjhdkjdlkjljkdljdljkdlkjdlwldklkwjdkjwkdjwkjdkljsdjadjjdfkaejdfjdfjqefjdhjhhhdwejdhqkdjh3uwhd
  expiration: 3600000
  refresh_token_duration: 86400000

